#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = ["pdt-cli"]
# ///
"""Generated by scripts/sync_apps.py. PDT_SMOKE_TOKEN proves PDT_ENV_JSON reached this job."""

from pathlib import Path

from pdt.config import ConfigError, check_env, load_env, merged_app
from pdt.utils.log import die, log


def main():
    app_dir = Path(__file__).resolve().parent
    try:
        app = merged_app(app_dir.name)
    except ConfigError as error:
        die(1, str(error))

    load_env(app_dir)
    problems = check_env(app["env"])
    if problems:
        die(1, "Environment check failed.", problems=problems)

    log(
        "info",
        app["config"]["greeting"],
        app=app_dir.name,
        provider=app["platform"].get("provider"),
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
