#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = ["pdt-cli[apps]"]
# ///
"""Generated by scripts/sync_apps.py. PDT_SMOKE_TOKEN proves PDT_ENV_JSON reached this job."""

import os
from pathlib import Path

from pdt.config import ConfigError, check_env, load_env, merged_app
from pdt.utils.log import die, log
from pdt.utils import storage


def main():
    app_dir = Path(__file__).resolve().parent
    try:
        app = merged_app(app_dir.name)
    except ConfigError as error:
        die(1, str(error))

    load_env(app_dir)
    problems = check_env(app["env"])
    expected = set(app["env"].get("optional") or [])
    problems.extend(
        f"missing verification env var {name}"
        for name in expected if not os.environ.get(name, "").strip())
    if problems:
        die(1, "Environment check failed.", problems=problems)

    if app["name"].endswith("-a") and app["storage"]:
        storage.store().fs().pipe_file(
            "verify.csv", b"name,value\nverification,1\n")

    log(
        "info",
        app["config"]["greeting"],
        app=app_dir.name,
        provider=app["platform"].get("provider"),
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
