# Generated by Django 6.1.1 on 2026-09-24 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('synced_at', models.DateTimeField(null=True)),
                ('sync_error', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='gui.project')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=500)),
                ('started', models.DateTimeField()),
                ('ended', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=20)),
                ('exit_code', models.IntegerField(null=True)),
                ('logs_synced_at', models.DateTimeField(null=True)),
                ('logs_error', models.TextField(blank=True, default='')),
                ('artifacts_synced_at', models.DateTimeField(null=True)),
                ('artifacts_error', models.TextField(blank=True, default='')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='gui.app')),
            ],
            options={
                'ordering': ['-started'],
                'unique_together': {('app', 'run_id')},
            },
        ),
        migrations.CreateModel(
            name='LogLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('time', models.DateTimeField(null=True)),
                ('level', models.CharField(blank=True, default='', max_length=10)),
                ('message', models.TextField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='gui.run')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024)),
                ('size', models.BigIntegerField(null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='gui.run')),
            ],
            options={
                'ordering': ['path'],
            },
        ),
    ]
