# Generated by Django 6.1.1 on 2026-09-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=1024)),
                ('started', models.DateTimeField()),
                ('ms', models.IntegerField()),
                ('ok', models.BooleanField()),
            ],
            options={
                'ordering': ['-started'],
            },
        ),
        migrations.AddField(
            model_name='run',
            name='artifacts_by_time',
            field=models.BooleanField(default=False),
        ),
    ]
