# Generated by Django 6.1.1 on 2026-09-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0002_timing_and_artifacts_by_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='history_synced_at',
            field=models.DateTimeField(null=True),
        ),
    ]
